import{S as q,a as y,i as w}from"./assets/vendor-5401a4b0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();let f;function P({largeImageURL:e,webformatURL:o,tags:a,likes:l,views:t,comments:r,downloads:i}){return`<li class="gallery-item">
        <a class="gallery-link" href="${e}">
            <img class="gallery-image" src="${o}" alt="${a}" />
        </a>
        <div class="info-box">
            <p>Likes:<span> ${l}</span></p>
            <p>Views:<span> ${t}</span></p>
            <p>Comments:<span> ${r}</span></p>
            <p>Downloads:<span> ${i}</span> </p>
        </div>
    </li>`}function h(e){const o=e.map(P).join("");n.gallery.insertAdjacentHTML("beforeend",o),f?x():v()}function v(){f=new q(".gallery a",{captionDelay:250,captionsData:"alt",captionPosition:"bottom"})}function x(){f.refresh()}const b=15;async function L(){return y.defaults.baseURL="https://pixabay.com/api/",(await y.get("",{params:{key:"42262858-7b31826aafbc45fb5436f2ee9",image_type:"photo",orientation:"horizontal",safesearch:"true",q:c,page:s,per_page:b}})).data}let c="",s=1;const n={formEl:document.querySelector(".form"),inputEl:document.querySelector(".query"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),btnLoad:document.querySelector(".load-more-btn")},m=n.gallery.querySelector(".gallery-item");n.formEl.addEventListener("submit",E);n.btnLoad.addEventListener("click",F);async function E(e){if(e.preventDefault(),u(),c=e.target.elements.query.value.trim(),!c){d("Please fill in the input field");return}try{g();const a=await L(s,c);a.hits.length>0?(h(a.hits),M(),O()):(g(),p(),d("Sorry, there are no images matching your search query. Please try again!")),S(a.totalHits,s)}catch(a){console.error("Error data:",a)}finally{u(),e.target.reset()}}async function F(){u(),s+=1;const e=await L();h(e.hits),S(e.totalHits,s),u()}function u(){n.loader.classList.toggle("hidden")}function d(e){w.show({message:e,messageColor:"#FFFFFF",backgroundColor:"#B51B1B",position:"topRight"})}function M(){n.btnLoad.style.display="block"}function p(){n.btnLoad.style.display="none"}function O(){if(m){const e=m.getClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}function g(){n.gallery.innerHTML="",p()}function S(e,o){Math.ceil(e/b)===o&&(p(),d("We're sorry, but you've reached the end of search results."))}
//# sourceMappingURL=commonHelpers.js.map
